# Generated by Django 2.2.8 on 2021-02-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210226_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfeedback',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
