# Generated by Django 2.2.8 on 2021-02-28 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_postfeedback_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postfeedback',
            name='type_of_feedback',
        ),
    ]
